### ISSUE TITLE
Question: regarding single game stats

### ISSUE THREAD

**Issue by derocknc** [J-Swift/cod-stats#3]
I noticed in your app you've been able to get single game records (ie. most kills in a game, etc). Since this information isn't available in the API call for lifetime stats, `MWBattleData` I'm wondering where you were able to get that from. I'm able to get last 20 game stats from `MWcombatwz` but can't seem to find a working call to get EVERY match. It seems like you'd have to make a call for every single match a person has played and then find the highest number of kills, which seems costly, but not sure there's another way to do it.  I'm wondering if you have just started logging each match in your DB as they are played and youre going off of that data or if you know of a way to get that data by other means.  Thanks for any help!

**Comment by J-Swift** [comment]
Most of the data you see is manually derived based off a persons individual games. I pull every single game for the person, filter out what I dont care about, normalize the data, then run reporting.

The data is all pulled by the `fetcher` (https://github.com/J-Swift/cod-stats/blob/master/fetcher/fetch_matches.ts). First I pull a players entire match history (1000 at a time) and then query those games 20 at a time. People generally have less than 2k games, so thats only ~25-100 api calls to get a persons entire match history on the first run. After that you will only need to do ~5 api calls to make sure you are up to date on them.
